TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=warehouse
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=item
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=district
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=customer
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=stock
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=order
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=neworder
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=orderline
TPCCDatabaseGenerator --ConnectionString="Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword" --Start=1 --End=2 --Tablename=history
