TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNwarehouse
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNitem
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNdistrict
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNcustomer
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNstock
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNorder
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNneworder
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNorderline
TPCCDatabaseGenerator \SRironman \Dtpccdb \SW1 \EW2 \TNhistory
